[package]
name = "id3-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
binread = "2.2.0"
modular-bitfield = "0.11.2"
thiserror = "1.0.44"
